apiVersion: v1
kind: Template
metadata:
  name: connector
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: connector
    spec:
      envName: ${ENV_NAME}
      title: "Manage configuration"
      routePrefix: insights
      deploymentRepo: https://github.com/RedHatInsights/sed-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /insights/connector
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: Remote Host Configuration
          expandable: true
          routes:
            - appId: connector
              title: Manage configuration
              href: /insights/connector
      module:
        manifestLocation: /apps/connector/fed-mods.json
        modules:
          - id: connector
            module: ./RootApp
            routes:
              - pathname: /insights/connector
        moduleID: connector
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/sed-frontend
